[package]
name = "uno-hal-macro"
version = "0.1.0"
authors = ["FrozenyDark <dmitriy.steshenko@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.114", features = ["full"] }
